package appinventario.views;
import appinventario.controllers.UsuarioController;
import appinventario.utils.LoginResult;
import appinventario.utils.UserSession;
import appinventario.views.Administrador.frmAdministradorPasswordView;

import java.awt.Color;
import java.awt.Point;
import javax.swing.JOptionPane;

public class frmLoginView extends javax.swing.JFrame {

    private static int initialX;
    private static int initialY;
    
    private final UsuarioController controlador;
    /**
     * Creates new form frmLoginView
     */
    public frmLoginView() {
        this.setUndecorated(true);
        initComponents();
        this.controlador = new UsuarioController();
        btnLogin.addActionListener(evt -> btnLoginActionPerformed());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(0,0,0,0));
        setForeground(java.awt.Color.white);
        setLocation(new java.awt.Point(100, 100));
        setMaximumSize(new java.awt.Dimension(297, 359));
        setMinimumSize(new java.awt.Dimension(297, 359));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(297, 359));
        jPanel1.setMinimumSize(new java.awt.Dimension(297, 359));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(297, 359));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/x.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 20, 20));

        txtUsername.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsername.setToolTipText("");
        txtUsername.setBorder(null);
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 199, 220, 30));

        txtPassword.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setBorder(null);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 246, 220, 30));

        btnLogin.setBorder(null);
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 140, 32));

        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.png"))); // NOI18N
        lblbackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblbackgroundMouseDragged(evt);
            }
        });
        lblbackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblbackgroundMousePressed(evt);
            }
        });
        jPanel1.add(lblbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 359));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblbackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackgroundMousePressed
        initialX = evt.getX();
        initialY = evt.getY();
    }//GEN-LAST:event_lblbackgroundMousePressed

    private void lblbackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackgroundMouseDragged
        int deltaX = evt.getX() - initialX;
        int deltaY = evt.getY() - initialY;
        Point location = this.getLocation();
        this.setLocation((int) (location.getX() + deltaX), (int) (location.getY() + deltaY));
    }//GEN-LAST:event_lblbackgroundMouseDragged

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnLoginActionPerformed() {                                         
        char[] passwordChars = this.txtPassword.getPassword();
        String password = new String(passwordChars);
        LoginResult rs = controlador.validarUsuario(this.txtUsername.getText(), password);
        if (rs.isSuccess()) { 
            UserSession.getInstancia().setUser(rs.getUser());
            if (rs.getUser().getforcePass()) {
                frmAdministradorPasswordView nwpass = new frmAdministradorPasswordView(this, true);
                nwpass.setVisible(true);
            }
            frmMenu.main(null);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "DATOS INCORRECTOS","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }                                                                                                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
