package appinventario.views.Producto;

import appinventario.controllers.ProductoController;
import appinventario.models.Producto;
import javax.swing.JOptionPane;

public class frmProductoAddView extends java.awt.Dialog {
    
    private final ProductoController controlador;
    private Producto producto;

    public frmProductoAddView(java.awt.Frame parent, boolean modal, ProductoController controlador) {
        super(parent, modal);
        initComponents();
        this.controlador = controlador;
        producto = new Producto();
    }

    private boolean validarDatos() {
        if (this.txtNombre.getText().isEmpty() || this.txtCategoria.getText().isEmpty() || this.txtDescripcion.getText().isEmpty() || this.txtPrecio.getText().isEmpty() || this.txtUnidadDeMedida.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtitulo1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnGuar1 = new javax.swing.JButton();
        txtUnidadDeMedida = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(597, 449));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        txtitulo1.setBackground(new java.awt.Color(255, 51, 51));
        txtitulo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Nombre:");
        txtitulo1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 117, -1, -1));

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtitulo1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 114, 402, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Unidad de Medida");
        txtitulo1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 314, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Categoria:");
        txtitulo1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 274, -1, -1));

        txtPrecio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtitulo1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 216, 402, -1));

        txtCategoria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtitulo1.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 271, 402, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Precio:");
        txtitulo1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 222, -1, -1));

        btnGuar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGuar1.setText("REGISTRAR");
        btnGuar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuar1ActionPerformed(evt);
            }
        });
        txtitulo1.add(btnGuar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 370, 123, 50));

        txtUnidadDeMedida.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtitulo1.add(txtUnidadDeMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 314, 402, -1));

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel11.setText("REGISTRAR PRODUCTO");
        txtitulo1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Descripción:");
        txtitulo1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 167, -1, -1));
        txtitulo1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 166, 402, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bgadmin.png"))); // NOI18N
        lblBackground.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtitulo1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnGuar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuar1ActionPerformed
        if (validarDatos()) {
            producto.setNombre(this.txtNombre.getText());
            producto.setCategoria(this.txtCategoria.getText());
            producto.setDescripcion(this.txtDescripcion.getText());
            double precio= Double.parseDouble(this.txtPrecio.getText());
            producto.setPrecio(precio);
            producto.setUnidad_medida(this.txtUnidadDeMedida.getText());
            boolean rs = controlador.registrarProducto(producto);
            if (!rs) {
                JOptionPane.showMessageDialog(null, "ERROR AL REGISTRAR EL PRODUCTO","ERROR",JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "PRODUCTO REGISTRADO!!","CORRECTO",JOptionPane.INFORMATION_MESSAGE);
            }
            dispose();
        }
    }//GEN-LAST:event_btnGuar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuar1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtUnidadDeMedida;
    private javax.swing.JPanel txtitulo1;
    // End of variables declaration//GEN-END:variables
}
