package appinventario.views.Administrador;

import appinventario.controllers.AdminController;
import appinventario.models.Usuario;
import java.awt.Frame;
import javax.swing.JOptionPane;

public class frmAdministradorAddView extends java.awt.Dialog {

    private final AdminController controlador;
    private final Usuario user;
    
    public frmAdministradorAddView(Frame parent, boolean modal, AdminController controlador) {
        super(parent, modal);
        initComponents();
        // Codigo del controlador y modelo
        this.controlador = controlador;
        this.user = new Usuario();
    }

    private boolean validarDatos() {
        if (this.txtNombre.getText().isEmpty() || this.txtApellido.getText().isEmpty() || this.txtTelefono.getText().isEmpty() || this.txtUsuario.getText().isEmpty() || this.txtCargo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblNombre2 = new javax.swing.JLabel();
        lblApellido2 = new javax.swing.JLabel();
        lblUsuario2 = new javax.swing.JLabel();
        lblTelefono2 = new javax.swing.JLabel();
        lblAdmin2 = new javax.swing.JLabel();
        lblCargo2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        ckbAdmin = new javax.swing.JCheckBox();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(329, 350));
        setResizable(false);
        setTitle("AGREGAR USUARIO");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(329, 322));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblTitulo.setText("AGREGAR USUARIO");
        jPanel3.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 46, 16, 250));

        lblNombre2.setForeground(new java.awt.Color(0, 51, 102));
        lblNombre2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre2.setText("Nombre");
        lblNombre2.setPreferredSize(new java.awt.Dimension(44, 22));
        jPanel3.add(lblNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 104, -1));

        lblApellido2.setForeground(new java.awt.Color(0, 51, 102));
        lblApellido2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblApellido2.setText("Apellido");
        lblApellido2.setPreferredSize(new java.awt.Dimension(44, 22));
        jPanel3.add(lblApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 104, 25));

        lblUsuario2.setForeground(new java.awt.Color(0, 51, 102));
        lblUsuario2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario2.setText("Usuario");
        jPanel3.add(lblUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 104, 25));

        lblTelefono2.setForeground(new java.awt.Color(0, 51, 102));
        lblTelefono2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefono2.setText("Telefono");
        lblTelefono2.setPreferredSize(new java.awt.Dimension(46, 22));
        jPanel3.add(lblTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 104, 25));

        lblAdmin2.setForeground(new java.awt.Color(0, 51, 102));
        lblAdmin2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAdmin2.setText("¿Administrador?");
        jPanel3.add(lblAdmin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 104, 25));

        lblCargo2.setForeground(new java.awt.Color(0, 51, 102));
        lblCargo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCargo2.setText("Cargo");
        jPanel3.add(lblCargo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 104, 25));
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 154, -1));
        jPanel3.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 154, -1));
        jPanel3.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 154, -1));
        jPanel3.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 154, -1));
        jPanel3.add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 154, -1));
        jPanel3.add(ckbAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 154, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bgmain.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setPreferredSize(new java.awt.Dimension(329, 322));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (validarDatos()) {
            user.setNombre(this.txtNombre.getText());
            user.setApellido(this.txtApellido.getText());
            user.setTelefono(this.txtTelefono.getText());
            user.setUsuario(this.txtUsuario.getText());
            user.setCargo(this.txtCargo.getText());
            user.setAdmin(this.ckbAdmin.isSelected());
            user.setPassword("123");
            user.setforcePass(true);
            boolean rs = controlador.registrarUsuario(user);
            if (!rs) {
                JOptionPane.showMessageDialog(null, "ERROR AL REGISTRAR EL USUARIO","ERROR",JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "USUARIO REGISTRADO!! Su contraseña es 123","CORRECTO",JOptionPane.INFORMATION_MESSAGE);
            }
            dispose();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox ckbAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAdmin2;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblCargo2;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblTelefono2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
