package appinventario.views.Suministro;

import appinventario.controllers.ProductoController;
import appinventario.controllers.ProveedorController;
import appinventario.controllers.SuministroController;
import appinventario.models.Producto;
import appinventario.models.Proveedor;
import appinventario.models.Suministro;
import appinventario.utils.UserSession;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

public class frmSuministroAddView extends java.awt.Dialog {
    
    private final SuministroController controlador;
    private final ProductoController controlproducto;
    private final ProveedorController controlproveedor;
    private Suministro sum;
    private int cantidad;

    public frmSuministroAddView(java.awt.Frame parent, boolean modal, SuministroController controlador) {
        super(parent, modal);
        initComponents();
        this.controlador = controlador;
        this.controlproducto = new ProductoController();
        this.controlproveedor = new ProveedorController();
        sum = new Suministro();
        rellenar();
    }
    
    public void rellenar(){
        List<Producto> productos = this.controlproducto.obtenerTodosProductos();
        List<Proveedor> proveedores = this.controlproveedor.obtenerTodosProveedores();
        for (Producto pro : productos) {
            this.cbxProducto.addItem(pro.getNombre());
        }
        for (Proveedor prov : proveedores) {
            this.cbxProveedor.addItem(prov.getNombre());
        }
    }

    private boolean validarDatos() {
        if (this.cbxProducto.getSelectedItem() == null || this.cbxProveedor.getSelectedItem() == null || this.txtCantidad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (cantidad <= 0) {
            JOptionPane.showMessageDialog(null, "La cantidad de suministro no puede ser menor o igual a 0.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxProveedor = new javax.swing.JComboBox<>();
        cbxProducto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(423, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRAR SUMINISTRO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jPanel1.add(cbxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 250, 30));

        jPanel1.add(cbxProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 260, 30));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText("Cantidad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 80, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setText("Producto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 400, 10));
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 90, 29));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setText("Proveedor");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, -1));

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 150, 30));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bgadmin.png"))); // NOI18N
        lblBackground.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            cantidad = Integer.parseInt(this.txtCantidad.getText());
        } catch (NumberFormatException e) {
            cantidad = 0;
        }
        if (validarDatos()) {
            int idpro = this.cbxProducto.getSelectedIndex() + 1;
            int idprov = this.cbxProveedor.getSelectedIndex() + 1;
            Producto pro = this.controlproducto.obtenerProducto(idpro);
            Proveedor prov = this.controlproveedor.obtenerProveedor(idprov);
            sum.setProducto(pro);
            sum.setProveedor(prov);
            sum.setCantidad(cantidad);
            Date fecha = new Date();
            sum.setFechaIngreso(fecha);
            sum.setUsuario(UserSession.getInstancia().getUser());
            boolean rs = controlador.registrarSuministro(sum);
            if (!rs) {
                JOptionPane.showMessageDialog(null, "ERROR AL REGISTRAR EL SUMINISTRO", "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "SUMINISTRO REGISTRADO!!", "CORRECTO",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            dispose();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxProducto;
    private javax.swing.JComboBox<String> cbxProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
