package appinventario.views.Consumo;

import appinventario.controllers.ConsumoController;
import appinventario.controllers.ProductoController;
import appinventario.models.Consumo;
import appinventario.models.Producto;
import appinventario.utils.ProductoStock;
import appinventario.utils.UserSession;
import java.awt.HeadlessException;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

public class frmConsumoAddView extends java.awt.Dialog {
    
    private final ConsumoController controlador;
    private final ProductoController controlproducto;
    private final List<ProductoStock> productos;
    private int cantidadStock;
    private int cantidad;

    public frmConsumoAddView(java.awt.Frame parent, boolean modal, ConsumoController controlador, List<ProductoStock> productos) {
        super(parent, modal);
        initComponents();
        this.controlador = controlador;
        this.controlproducto = new ProductoController();
        this.productos = productos;
        rellenar();
    }
    
    private void rellenar(){
        for (ProductoStock pstock : productos) {
            this.cbxProducto.addItem(pstock.getNombre());
        }
    }

    private void setCantidadtxt(String nombre) {
        for (ProductoStock pstock : productos) {
            if (pstock.getNombre().equals(nombre)) {
                this.cantidadStock = pstock.getCantidad();
                this.txtCantidad.setText(this.cantidadStock + "");
            }
        }
    }

    private boolean validarDatos() {
        if (this.cbxProducto.getSelectedItem() == null || this.txtCantidad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (this.cantidad > this.cantidadStock || this.cantidad <= 0) {
            JOptionPane.showMessageDialog(null, "La cantidad de consumo no puede superar la cantidad en inventario.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxProducto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtCantidad = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(423, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRAR CONSUMO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        cbxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProductoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 260, 30));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText("Cantidad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 80, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setText("Producto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 400, 10));
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 150, 29));

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 150, 30));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bgmain.png"))); // NOI18N
        lblBackground.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 240));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            cantidad = Integer.parseInt(this.txtCantidad.getText());
        } catch (NumberFormatException e) {
            cantidad = 0;
        }
        if (validarDatos()) {
            Consumo consumo = new Consumo();
            String nombreProducto = "" + this.cbxProducto.getSelectedItem();
            Producto pro = this.controlproducto.obtenerProductoPorNombre(nombreProducto);
            consumo.setProducto(pro);
            consumo.setUsuario(UserSession.getInstancia().getUser());
            consumo.setCantidad(cantidad);
            Date fecha = new Date();
            consumo.setFechaSalida(fecha);
            boolean rs = controlador.registrarConsumo(consumo);
            if (!rs) {
                JOptionPane.showMessageDialog(null, "ERROR AL REGISTRAR EL CONSUMO", "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "CONSUMO REGISTRADO!!", "CORRECTO",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            dispose();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cbxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProductoActionPerformed
        String nom = cbxProducto.getSelectedItem() + "";
        setCantidadtxt(nom);
    }//GEN-LAST:event_cbxProductoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
