package appinventario.views.Consumo;

import appinventario.controllers.ConsumoController;
import appinventario.controllers.InventarioController;
import appinventario.models.Consumo;
import appinventario.tablas.ConsumoTableModel;
import appinventario.utils.ProductoStock;
import appinventario.views.BaseMover;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class frmConsumoView extends BaseMover {
    
    public static frmConsumoView instancia;
    private final ConsumoController controlador;

    public frmConsumoView() {
        initComponents();
        this.controlador = new ConsumoController();
        actualizarTabla();
    }
    
     // Funcion para la vista eliminar
    private void frmEliminarView() {
        if (this.txtID.getText() != null) {
            try {
                int id = Integer.parseInt(this.txtID.getText());
                Consumo con = controlador.obtenerConsumo(id);
                if (con.getId() > 0) {
                    int opcion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el suministro : [ " + con.getCantidad() + " de " + con.getProducto().getNombre() + " ] ?", "CUIDADO!", JOptionPane.YES_NO_OPTION);
                    if (opcion == JOptionPane.YES_OPTION) {
                        boolean rs = controlador.eliminarConsumo(id);
                        if (rs) {
                            JOptionPane.showMessageDialog(null, "CONSUMO ELIMINADO!!","CORRECTO",JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(null, "NO SE PUDO ELIMINAR EL CONSUMO","ERROR",JOptionPane.ERROR_MESSAGE);
                        }
                        actualizarTabla();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No existe ningun consumo con esa ID","ERROR",JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }
    // Funcion para la vista nuevo
    private void frmNewView() {
        InventarioController inv = new InventarioController();
        List<ProductoStock> productos = inv.pStock();
        if (productos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "NO EXISTE PRODUCTOS CON STOCK EN EL INVENTARIO", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            frmConsumoAddView addview = new frmConsumoAddView(this, true, this.controlador, productos);
            addview.setVisible(true);
            actualizarTabla();
        }
    }
    
    // Funcion para refrescar la tabla y visualizar los cambios
    private void actualizarTabla() {
        List<Consumo> con = controlador.obtenerTodosConsumos();
        ConsumoTableModel modelo = new ConsumoTableModel(con);
        this.tablaConsumo.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaConsumo = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 252), 4));
        jPanel1.setMaximumSize(new java.awt.Dimension(895, 470));
        jPanel1.setMinimumSize(new java.awt.Dimension(895, 470));
        jPanel1.setPreferredSize(new java.awt.Dimension(895, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/x.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 20, 20));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        jLabel1.setText("CONSUMO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        tablaConsumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaConsumo);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 157, 850, 290));

        btnAgregar.setBackground(new java.awt.Color(51, 255, 51));
        btnAgregar.setText("AGREGAR CONSUMO");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 180, 33));

        btnEliminar.setBackground(new java.awt.Color(255, 51, 0));
        btnEliminar.setText("ELIMINAR CONSUMO");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 180, 33));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 112, 40, 30));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bgadmin.png"))); // NOI18N
        lblBackground.setPreferredSize(new java.awt.Dimension(887, 462));
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        frmNewView();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        frmEliminarView();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    public static frmConsumoView getInstancia() {
        if (instancia == null) {
            instancia = new frmConsumoView();{
            instancia.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
            return instancia;
        } else {
            return instancia;
        }
    }
    
    public void visible(boolean visible) {
        instancia.setVisible(visible);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblClose;
    private javax.swing.JTable tablaConsumo;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
