package appinventario.views.Producto;

import appinventario.controllers.ProductoController;
import appinventario.models.Producto;
import javax.swing.JOptionPane;

public class frmProductoUpdateView extends java.awt.Dialog {
    
    private ProductoController controlador;
    private int id;
    private Producto producto;

    public frmProductoUpdateView(java.awt.Frame parent, boolean modal, ProductoController controlador, int id) {
        super(parent, modal);
        initComponents();
        this.controlador = controlador;
        this.id = id;
        this.producto = controlador.obtenerProducto(id);
        this.txtNombre.setText(producto.getNombre());
        this.txtCategoria.setText(producto.getCategoria());
        this.txtDescripcion.setText(producto.getDescripcion());
        String precio = producto.getPrecio() + "";
        this.txtPrecio.setText(precio);
        this.txtUnidadDeMedida.setText(producto.getUnidad_medida());
    }

    private boolean validarDatos() {
        if (this.txtNombre.getText().isEmpty() || this.txtCategoria.getText().isEmpty() || this.txtDescripcion.getText().isEmpty() || this.txtPrecio.getText().isEmpty() || this.txtUnidadDeMedida.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnGuar1 = new javax.swing.JButton();
        txtUnidadDeMedida = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(597, 449));
        setMinimumSize(new java.awt.Dimension(597, 449));

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Nombre:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 117, -1, -1));

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 114, 402, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Unidad de Medida");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 314, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Categoria:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 274, -1, -1));

        txtPrecio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 216, 400, -1));

        txtCategoria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 271, 400, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Precio:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 222, -1, -1));

        btnGuar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGuar1.setText("ACTUALIZAR");
        btnGuar1.setToolTipText("");
        btnGuar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 370, 123, 50));

        txtUnidadDeMedida.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(txtUnidadDeMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 314, 400, -1));

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel11.setText("MODIFICAR PRODUCTO");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Descripción:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 167, -1, -1));
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 166, 400, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bgadmin.png"))); // NOI18N
        lblBackground.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnGuar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuar1ActionPerformed
        if (validarDatos()) {
            producto.setNombre(this.txtNombre.getText());
            producto.setCategoria(this.txtCategoria.getText());
            producto.setDescripcion(this.txtDescripcion.getText());
            double precio= Double.parseDouble(this.txtPrecio.getText());
            producto.setPrecio(precio);
            producto.setUnidad_medida(this.txtUnidadDeMedida.getText());
            boolean rs = controlador.actualizarProducto(id, producto);
            if (!rs) {
                JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR EL PRODUCTO","ERROR",JOptionPane.ERROR_MESSAGE);
            }
            dispose();
        }
    }//GEN-LAST:event_btnGuar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuar1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtUnidadDeMedida;
    // End of variables declaration//GEN-END:variables
}
