package appinventario.views.Administrador;

import appinventario.controllers.AdminController;
import appinventario.models.Usuario;
import appinventario.tablas.UsuarioTableModel;
import appinventario.views.BaseMover;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

public class frmAdministradorView extends BaseMover {

    private final AdminController controlador;
    private static frmAdministradorView instancia;

    private frmAdministradorView() {
        initComponents();
        this.controlador = new AdminController();
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        btnClose = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        jButton3.setText("AGREGAR USUARIO");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);
        setUndecorated(true);
        setSize(new java.awt.Dimension(970, 480));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 252), 4));
        jPanel1.setPreferredSize(new java.awt.Dimension(940, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/admin.png"))); // NOI18N
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 150, 160));

        lblTitulo.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        lblTitulo.setText("ADMINISTRACIÓN DE USUARIOS");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 680, 47));

        btnAgregar.setBackground(new java.awt.Color(0, 204, 0));
        btnAgregar.setText("AGREGAR USUARIO");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 175, 33));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 640, 13));

        jScrollPane2.setMaximumSize(new java.awt.Dimension(980, 260));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(980, 260));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(980, 260));

        tablaUsuarios.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaUsuarios);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 900, 260));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/x.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, 20));

        btnEliminar.setBackground(new java.awt.Color(255, 51, 0));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 130, 33));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 40, 30));

        btnModificar.setBackground(new java.awt.Color(0, 0, 255));
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 130, 33));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bgadmin.png"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 932, 472));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // Codigo para seleccionar un elemento de la JTable
        if (evt.getClickCount() == 2) {
            JTable target = (JTable)evt.getSource();
            int row = target.getSelectedRow();
            int id = (int) target.getValueAt(row, 0); // Es la id del elemento de la JTable.
            frmUpdateView(id); // Invocamos al metodo main modificado para que reciba el id del usuario
        }
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    // Funcion para la vista update
    private void frmUpdateView(int id) {
        frmAdministradorUpdateView updateview = new frmAdministradorUpdateView(this, true, this.controlador, id);
        updateview.setVisible(true);
        actualizarTabla();
    }
    
    // Funcion para la vista nuevo
    private void frmNewView() {
        frmAdministradorAddView addview = new frmAdministradorAddView(this, true, this.controlador);
        addview.setVisible(true);
        actualizarTabla();
    }
    
    // Funcion para refrescar la tabla y visualizar los cambios
    private void actualizarTabla() {
        List<Usuario> user = controlador.obtenerTodosUsuarios();
        UsuarioTableModel modelo = new UsuarioTableModel(user);
        tablaUsuarios.setModel(modelo);
    }

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        frmNewView();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (this.txtID.getText() != null) {
            try {
                int id = Integer.parseInt(this.txtID.getText());
                Usuario user = controlador.obtenerUsuario(id);
                if (user.getId() > 0) {
                    int opcion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el usuario de " + user.getNombre() + " ?", "CUIDADO!", JOptionPane.YES_NO_OPTION);
                    if (opcion == JOptionPane.YES_OPTION) {
                        boolean rs = controlador.eliminarUsuario(id);
                        if (rs) {
                            JOptionPane.showMessageDialog(null, "USUARIO ELIMINADO!!","CORRECTO",JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(null, "NO SE PUDO ELIMINAR EL USUARIO","ERROR",JOptionPane.ERROR_MESSAGE);
                        }
                        actualizarTabla();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No existe ningun usuario con esa ID","ERROR",JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            this.txtID.setText("");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            if (!this.txtID.getText().isEmpty()) {
                int id = Integer.parseInt(this.txtID.getText());
                Usuario user = controlador.obtenerUsuario(id);
                if (user.getId() > 0) {
                    frmUpdateView(id);
                } else {
                    JOptionPane.showMessageDialog(null, "No existe ningun usuario con esa ID","ERROR",JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
        this.txtID.setText("");
    }//GEN-LAST:event_btnModificarActionPerformed

    public static frmAdministradorView getInstancia() {
        if (instancia == null) {
            instancia = new frmAdministradorView();
            instancia.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            return instancia;
        } else {
            return instancia;
        }
    }
    
    public void visible(boolean visible) {
        instancia.setVisible(visible);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
