package appinventario.views;

import java.awt.Point;
import appinventario.utils.UserSession;
import appinventario.views.Administrador.frmAdministradorView;
import appinventario.views.Consumo.frmConsumoView;
import appinventario.views.Producto.frmProductosView;
import appinventario.views.Proveedor.frmProveedoresView;
import appinventario.views.Suministro.frmSuministroView;


public class frmMenu extends javax.swing.JFrame {

    private static int initialX;
    private static int initialY;
    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        this.lblSaludo.setText(UserSession.getInstancia().getSaludo());
        btnUsuarios.addActionListener(evt -> btnUsuariosAccion());
        btnConsumos.addActionListener(evt -> btnConsumosAccion());
        btnProveedores.addActionListener(evt -> btnProveedoresAccion());
        btnProductos.addActionListener(evt -> btnProductosAccion());
        btnSuministros.addActionListener(evt -> btnSuministrosAccion());
    }

    private void btnUsuariosAccion() {
        frmAdministradorView.getInstancia().visible(true);
    }

    private void btnConsumosAccion() {
        frmConsumoView.getInstancia().visible(true);
    }
    
    private void btnProveedoresAccion() {
        frmProveedoresView.getInstancia().visible(true);
    }

    private void btnProductosAccion() {
        frmProductosView.getInstancia().visible(true);
    }
    
    private void btnSuministrosAccion() {
        frmSuministroView.getInstancia().visible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnConsumos = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnSuministros = new javax.swing.JButton();
        lblClose = new javax.swing.JLabel();
        lblSaludo = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        jButton3.setText("PRODUCTO");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 252), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConsumos.setText("CONSUMOS");
        btnConsumos.setBorder(null);

        jPanel1.add(btnConsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 370, 300, 40));

        btnUsuarios.setText("USUARIOS");
        btnUsuarios.setBorder(null);

        jPanel1.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 170, 300, 40));

        btnProveedores.setText("PROVEEDORES");
        btnProveedores.setBorder(null);

        jPanel1.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 220, 300, 40));

        btnProductos.setText("PRODUCTOS");
        btnProductos.setBorder(null);

        jPanel1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 270, 300, 40));

        btnSuministros.setText("SUMINISTROS");
        btnSuministros.setBorder(null);
        
        jPanel1.add(btnSuministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 320, 300, 40));

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/x.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 15, 20, 20));

        lblSaludo.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lblSaludo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaludo.setText("BIENVENIDO ");
        jPanel1.add(lblSaludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 140, 200, -1));

        lblPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user-chef.png"))); // NOI18N
        jPanel1.add(lblPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 30, 100, 100));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bgmain.png"))); // NOI18N
        lblBackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBackgroundMouseDragged(evt);
            }
        });
        lblBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBackgroundMousePressed(evt);
            }
        });
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 436, 432));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblBackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundMousePressed
        initialX = evt.getX();
        initialY = evt.getY();
    }//GEN-LAST:event_lblBackgroundMousePressed

    private void lblBackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundMouseDragged
        int deltaX = evt.getX() - initialX;
        int deltaY = evt.getY() - initialY;
        Point location = this.getLocation();
        this.setLocation((int) (location.getX() + deltaX), (int) (location.getY() + deltaY));
    }//GEN-LAST:event_lblBackgroundMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsumos;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnSuministros;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblSaludo;
    // End of variables declaration//GEN-END:variables
}
