package appinventario.views.Proveedor;

import appinventario.controllers.ProveedorController;
import appinventario.models.Proveedor;
import javax.swing.JOptionPane;

public class frmProveedorAddView extends java.awt.Dialog {
    
    private final ProveedorController controlador;
    private Proveedor proveedor;

    public frmProveedorAddView(java.awt.Frame parent, boolean modal, ProveedorController controlador) {
        super(parent, modal);
        initComponents();
        this.controlador = controlador;
        proveedor = new Proveedor();
    }

    private boolean validarDatos() {
        if (this.txtNombre.getText().isEmpty() || this.txtTelefono.getText().isEmpty() || this.txtEmail.getText().isEmpty() || this.txtDireccion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtitulo1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(500, 384));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        txtitulo1.setBackground(new java.awt.Color(255, 51, 51));
        txtitulo1.setMinimumSize(new java.awt.Dimension(500, 366));
        txtitulo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Nombre:");
        txtitulo1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 110, -1, -1));

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtitulo1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 107, 297, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Direccion:");
        txtitulo1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 267, -1, -1));

        txtEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtitulo1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 209, 297, -1));

        txtDireccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtitulo1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 264, 297, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Email:");
        jLabel10.setToolTipText("");
        txtitulo1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 215, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGuardar.setText("REGISTRAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        txtitulo1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 307, 123, 50));

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        jLabel11.setText("REGISTRAR PROVEEDOR");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtitulo1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 38, 338, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Telefono:");
        txtitulo1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 160, -1, -1));
        txtitulo1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 159, 297, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bgadmin.png"))); // NOI18N
        lblBackground.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtitulo1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (validarDatos()) {
            proveedor.setNombre(this.txtNombre.getText());
            proveedor.setTelefono(this.txtTelefono.getText());
            proveedor.setEmail(this.txtEmail.getText());
            proveedor.setDireccion(this.txtDireccion.getText());
            boolean rs = controlador.registrarProveedor(proveedor);
            if (!rs) {
                JOptionPane.showMessageDialog(null, "ERROR AL REGISTRAR EL PROVEEDOR","ERROR",JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "PROVEEDOR REGISTRADO!!","CORRECTO",JOptionPane.INFORMATION_MESSAGE);
            }
            dispose();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JPanel txtitulo1;
    // End of variables declaration//GEN-END:variables
}
